# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    - python -m pip install -r requirements.txt
    - python -m pip install .
    - python -m sphinx -T -b html docs/source $READTHEDOCS_OUTPUT/html
